import type { AutomationStageDefinition } from '../types'
import { step } from './shared'

export const END_OF_DAY_STAGE: AutomationStageDefinition = {
  id: 'end-of-day',
  title: '6. End-of-day check',
  shortTitle: 'End-of-day check',
  purpose: 'Find unscheduled patients and force every blocker to a named owner.',
  trigger: "WCW's end-of-day cutoff is reached.",
  successDefinition: 'Every due referral is scheduled, owned for follow-up, or escalated.',
  implementationStatus: 'partial',
  microsteps: [
    step({
      id: 'find-unscheduled',
      name: 'Find Unscheduled Patients',
      description: 'Identify due referrals without a verified appointment.',
      system: 'Monday.com / DRK monitor',
      next: 'Notify Case Manager and Lead',
      input: 'Active due referrals',
      output: 'Unscheduled patients and blockers',
      validation: 'Source failures are not treated as unscheduled patients.',
      implementationStatus: 'partial',
    }),
    step({
      id: 'notify-owner',
      name: 'Notify Case Manager and Lead',
      description: 'Send the patient and blocker to the responsible owner.',
      system: 'Notification service',
      next: 'Escalate Unresolved Cases',
      input: 'Patient, owner, and blocker',
      output: 'Follow-up delivered',
      validation: 'Only one active follow-up exists per patient and day.',
      implementationStatus: 'partial',
    }),
    step({
      id: 'escalate-unresolved',
      name: 'Escalate Unresolved Cases',
      description: 'Escalate blockers that remain unresolved after follow-up.',
      system: 'Management escalation',
      next: 'Verify Scheduling Resolution',
      input: 'Unresolved blocker and follow-up history',
      output: 'Named management escalation',
      validation: 'Each unresolved case is escalated once with evidence.',
      implementationStatus: 'partial',
    }),
    step({
      id: 'verify-resolution',
      name: 'Verify Scheduling Resolution',
      description: 'Confirm the final scheduling state and weekly-cycle eligibility.',
      system: 'Workflow monitor',
      next: 'Begin Weekly Visit Cycle',
      input: 'Refreshed appointment fields',
      output: 'Scheduled or still unresolved',
      validation: 'Only explicit appointment evidence closes the exception.',
      implementationStatus: 'partial',
    }),
  ],
}
