import type { AutomationStageDefinition } from '../types'
import { step } from './shared'

export const HANDOFF_STAGE: AutomationStageDefinition = {
  id: 'handoff',
  title: '2. Handoff',
  shortTitle: 'Handoff',
  purpose: 'Create the patient records and confirm both destinations received the referral.',
  trigger: 'The referral is approved for handoff.',
  successDefinition: 'Monday.com and DRK contain verified records for the same referral.',
  implementationStatus: 'partial',
  microsteps: [
    step({
      id: 'notify-referral-source',
      name: 'Notify Referral Source',
      description: 'Confirm that WCW received the referral.',
      system: 'Outlook',
      next: 'Create Monday.com Record',
      input: 'Approved referral and source contact',
      output: 'Acknowledgment delivered',
      validation: 'The message identifies the correct patient and referral source.',
    }),
    step({
      id: 'create-monday-record',
      name: 'Create Monday.com Record',
      description: 'Write the approved referral into the Master Sheet.',
      system: 'Monday.com',
      next: 'Create or Update DRK Chart',
      input: 'Approved patient fields',
      output: 'Master Sheet item',
      validation: 'A repeated request cannot create a duplicate item.',
    }),
    step({
      id: 'create-update-drk',
      name: 'Create or Update DRK Chart',
      description: 'Create the chart or update the confirmed patient match.',
      system: 'DRK',
      next: 'Verify Completed Handoff',
      input: 'Approved referral and duplicate result',
      output: 'DRK chart',
      validation: 'Unresolved identity matches block the write.',
      implementationStatus: 'planned',
    }),
    step({
      id: 'verify-handoff',
      name: 'Verify Completed Handoff',
      description: 'Confirm that Monday.com and DRK contain the expected patient.',
      system: 'Workflow monitor',
      next: 'Begin Assignment',
      input: 'Monday.com and DRK receipts',
      output: 'Verified handoff',
      validation: 'Only the failed destination is retried.',
    }),
  ],
}
