import type { AutomationStageDefinition } from '../types'
import { step } from './shared'

export const SCHEDULING_STAGE: AutomationStageDefinition = {
  id: 'scheduling',
  title: '5. Scheduling',
  shortTitle: 'Scheduling',
  purpose: 'Confirm an appointment within 24-48 hours and record it across WCW systems.',
  trigger: 'The provider selection is confirmed.',
  successDefinition: 'The appointment is verified, or a scheduling blocker is explicit.',
  implementationStatus: 'planned',
  microsteps: [
    step({
      id: 'send-referral-provider',
      name: 'Send Referral to Provider',
      description: 'Deliver the approved referral to the selected provider.',
      system: 'Referral delivery',
      next: 'Capture Provider Response',
      input: 'Approved referral and selected provider',
      output: 'Delivery receipt',
      validation: 'The referral and provider match the approved selection.',
      implementationStatus: 'planned',
    }),
    step({
      id: 'capture-provider-response',
      name: 'Capture Provider Response',
      description: 'Record acceptance, decline, availability, or timeout.',
      system: 'Response monitor',
      next: 'Confirm and Record Appointment',
      input: 'Provider response',
      output: 'Current availability or blocker',
      validation: 'Only responses tied to this referral are accepted.',
      implementationStatus: 'planned',
    }),
    step({
      id: 'confirm-record-appointment',
      name: 'Confirm and Record Appointment',
      description: 'Choose a slot and write it into Monday.com and DRK.',
      system: 'WCW scheduling / Monday.com / DRK',
      next: 'Verify Scheduling Complete',
      input: 'Available appointment choices',
      output: 'Appointment write receipts',
      validation: 'The selected slot is written once and tied to the decision.',
      implementationStatus: 'planned',
    }),
    step({
      id: 'verify-scheduling',
      name: 'Verify Scheduling Complete',
      description: 'Confirm the appointment and completion status agree across systems.',
      system: 'Workflow monitor',
      next: 'Enter End-of-Day Check',
      input: 'Expected appointment and destination receipts',
      output: 'Scheduled or blocked',
      validation: 'The stage closes only when expected and observed values agree.',
      implementationStatus: 'planned',
    }),
  ],
}
