import type { AutomationStageDefinition } from '../types'
import { step } from './shared'

export const WEEKLY_STAGE: AutomationStageDefinition = {
  id: 'weekly',
  title: '7. Weekly visit cycle',
  shortTitle: 'Weekly visit cycle',
  purpose: 'Turn each recorded visit outcome into the correct next action.',
  trigger: 'An active patient has expected weekly visit activity.',
  successDefinition: 'The visit status and required follow-up are recorded and owned.',
  implementationStatus: 'partial',
  microsteps: [
    step({
      id: 'record-visit-outcome',
      name: 'Record Visit Outcome',
      description: 'Read the DRK progress note and record Seen or Not Seen.',
      system: 'DRK / Monday.com',
      next: 'Apply Weekly Status Rules',
      input: 'Current progress note and visit fields',
      output: 'Verified visit outcome',
      validation: 'Missing data remains unknown and never becomes Not Seen.',
      implementationStatus: 'partial',
    }),
    step({
      id: 'apply-weekly-rules',
      name: 'Apply Weekly Status Rules',
      description: 'Update consecutive misses, hold, healing, expiration, and discharge-review status.',
      system: 'Visit rules',
      next: 'Assign Required Follow-Up',
      input: 'Visit outcome and previous patient state',
      output: 'Required action',
      validation: 'Clinical and discharge decisions remain human-controlled.',
      implementationStatus: 'partial',
    }),
    step({
      id: 'assign-follow-up',
      name: 'Assign Required Follow-Up',
      description: 'Assign rescheduling, hold, QA, or discharge review to the responsible team.',
      system: 'Workflow routing',
      next: 'Verify Weekly Cycle Result',
      input: 'Rule result and supporting evidence',
      output: 'Owned follow-up action',
      validation: 'Open actions are updated instead of duplicated.',
      implementationStatus: 'partial',
    }),
    step({
      id: 'verify-weekly-result',
      name: 'Verify Weekly Cycle Result',
      description: 'Confirm the status update and keep unresolved work open.',
      system: 'Workflow monitor',
      next: 'Continue Weekly Visit Cycle',
      input: 'Status write and follow-up receipt',
      output: 'Closed cycle or open action',
      validation: 'Human approval remains required for clinical and discharge actions.',
      implementationStatus: 'partial',
    }),
  ],
}
