"""Fourteen coherent fake referrals: two for each supplied layout family."""

from __future__ import annotations

from .models import SyntheticReferral, SyntheticService


def _case(
    slug: str,
    layout: str,
    scenario: str,
    scan_style: str,
    name: str,
    dob: str,
    sex: str,
    phone: str | None,
    address: str | None,
    mrn: str,
    facility: str,
    provider: str,
    diagnosis: str | None,
    icd10: list[str],
    insurer: str | None,
    insurance_id: str | None,
    services: list[SyntheticService],
    *,
    outcome: str = "ready_for_human_approval",
    monday_duplicate: str = "no_candidates_found",
    drk_duplicate: str = "clear_to_create",
    referral_date: str = "08/11/2026",
    admission_date: str | None = "08/08/2026",
) -> SyntheticReferral:
    number = int("".join(ch for ch in mrn if ch.isdigit())[-3:] or "100")
    return SyntheticReferral(
        slug=slug,
        layout=layout,
        scenario=scenario,
        scan_style=scan_style,
        patient_name=name,
        patient_dob=dob,
        patient_sex=sex,
        patient_phone=phone,
        patient_address=address,
        patient_mrn=mrn,
        referral_date=referral_date,
        admission_date=admission_date,
        referring_facility=facility,
        referring_provider_name=provider,
        referring_phone=f"(323) 555-{1000 + number:04d}",
        referring_fax=f"(323) 555-{2000 + number:04d}",
        diagnosis_text=diagnosis,
        icd10_codes=icd10,
        insurance_provider=insurer,
        insurance_id=insurance_id,
        insurance_group_number=f"SYN-GRP-{number:03d}" if insurer else None,
        requested_services=services,
        emergency_contact=f"TEST Contact {number}, (310) 555-{3000 + number:04d}",
        expected_outcome=outcome,
        expected_monday_duplicate=monday_duplicate,
        expected_drk_duplicate=drk_duplicate,
    )


WOUND_EVAL = SyntheticService(
    service="Wound Care",
    frequency="Initial evaluation",
    instructions="Evaluate wound and establish treatment plan.",
)
WEEKLY_WOUND = SyntheticService(
    service="Skilled wound care",
    frequency="3 times weekly",
    instructions="Cleanse, measure, photograph, and dress wound per orders.",
)


SYNTHETIC_CASES: tuple[SyntheticReferral, ...] = (
    _case(
        "chart-marisol-vega", "patient_chart", "complete dense patient chart", "clean",
        "VEGA, MARISOL", "03/12/1948", "Female", "(310) 555-4101",
        "1840 Training Avenue, Long Beach, CA 90806", "SYN1001",
        "Harbor Community Clinic", "Elena Park, MD",
        "Venous stasis ulcer of left lower leg with edema.", ["I83.023", "L97.321"],
        "SampleCare Medicare Advantage", "SYN-MA-1001", [WOUND_EVAL, WEEKLY_WOUND],
    ),
    _case(
        "chart-thomas-reed", "patient_chart", "missing patient phone", "fax",
        "REED, THOMAS", "09/24/1956", "Male", None,
        "772 Fictional Court, Torrance, CA 90501", "SYN1002",
        "South Bay Primary Care", "Aaron Mills, DO",
        "Diabetic ulcer of right heel with fat layer exposed.", ["E11.621", "L97.412"],
        "Example Medicare Part B", "SYN-MB-1002", [WOUND_EVAL],
        outcome="blocked_missing_threshold",
    ),
    _case(
        "wcw-denise-holloway", "wcw_handwritten", "complete handwritten referral", "clean",
        "HOLLOWAY, DENISE", "01/07/1962", "Female", "(424) 555-4103",
        "911 Sample Palm Drive, Inglewood, CA 90301", "SYN1003",
        "Pacific Horizon Home Health", "Nadia Flores, NP",
        "Stage 3 pressure injury of sacral region.", ["L89.153"],
        "Training Health PPO", "SYN-PPO-1003", [WOUND_EVAL],
    ),
    _case(
        "wcw-calvin-brooks", "wcw_handwritten", "insurance absent", "fax",
        "BROOKS, CALVIN", "11/18/1944", "Male", "(562) 555-4104",
        "62 Demo Street, Carson, CA 90745", "SYN1004",
        "Golden State Home Health", "Priya Raman, MD",
        "Non-healing surgical wound of abdomen.", ["T81.89XA"],
        None, None, [WOUND_EVAL], outcome="manual_review_required",
    ),
    _case(
        "hospital-lucia-moreno", "hospital_fax", "hospital packet complete", "clean",
        "MORENO, LUCIA", "06/03/1951", "Female", "(213) 555-4105",
        "145 Test Harbor Road, San Pedro, CA 90731", "SYN1005",
        "Hubert H. Humphrey Training Center", "Michael Santos, MD",
        "Open wound of left foot following cellulitis admission.", ["S91.302A", "L03.116"],
        "Medi-Cal Sample Plan", "SYN-MCAL-1005", [WOUND_EVAL],
    ),
    _case(
        "hospital-arthur-bell", "hospital_fax", "Monday duplicate candidate", "fax",
        "BELL, ARTHUR", "02/20/1947", "Male", "(323) 555-4106",
        "808 Mockingbird Lane, Los Angeles, CA 90044", "SYN1006",
        "Hubert H. Humphrey Training Center", "Michelle Grant, MD",
        "Unstageable pressure injury of right heel.", ["L89.610"],
        "ExampleCare HMO", "SYN-HMO-1006", [WOUND_EVAL],
        monday_duplicate="duplicate_found", outcome="manual_review_required",
    ),
    _case(
        "facesheet-renee-lawson", "hospital_facesheet", "DRK duplicate candidate", "clean",
        "LAWSON, RENEE", "12/14/1959", "Female", "(424) 555-4107",
        "320 Prototype Way Apt 4, Gardena, CA 90247", "SYN1007",
        "Providence Training Medical Center", "Alan Rivers, MD",
        "Cellulitis with draining ulcer of left calf.", ["L03.116", "L97.222"],
        "Sample LA Care Medi-Cal", "SYN-LAC-1007", [WOUND_EVAL],
        drk_duplicate="duplicate_found", outcome="manual_review_required",
    ),
    _case(
        "facesheet-gordon-price", "hospital_facesheet", "conflicting operational dates", "fax",
        "PRICE, GORDON", "05/29/1941", "Male", "(310) 555-4108",
        "77 Workflow Boulevard, Compton, CA 90220", "SYN1008",
        "Providence Training Medical Center", "Rita Shah, MD",
        "Pressure injury of left hip, stage 2.", ["L89.222"],
        "Example Medicare Advantage", "SYN-MA-1008", [WOUND_EVAL],
        outcome="manual_review_required", referral_date="08/11/2026", admission_date="08/04/2026",
    ),
    _case(
        "homehealth-celeste-navarro", "home_health_fax", "concise home-health order", "clean",
        "NAVARRO, CELESTE", "08/08/1966", "Female", "(818) 555-4109",
        "1825 Synthetic Terrace, Tarzana, CA 91356", "SYN1009",
        "DNA Training Home Health", "David Marin, DPM",
        "Stage 2 coccyx pressure injury measuring 2.1 x 1.4 cm.", ["L89.152"],
        "SampleCare Medicare", "SYN-MCR-1009", [WOUND_EVAL, WEEKLY_WOUND],
    ),
    _case(
        "homehealth-leonard-kim", "home_health_fax", "address missing from fax", "fax",
        "KIM, LEONARD", "10/17/1953", "Male", "(818) 555-4110", None, "SYN1010",
        "DNA Training Home Health", "Rebecca Lin, NP",
        "Skin tear of right forearm requiring wound evaluation.", ["S51.811A"],
        "Example Medicare Part B", "SYN-MB-1010", [WOUND_EVAL],
        outcome="blocked_missing_threshold",
    ),
    _case(
        "discharge-diane-mercer", "discharge_packet", "complete discharge referral", "clean",
        "MERCER, DIANE", "04/26/1949", "Female", "(760) 555-4111",
        "420 Evaluation Road, Barstow, CA 92311", "SYN1011",
        "Barstow Community Training Hospital", "Natalie Lewis, RN",
        "Dehisced abdominal surgical wound requiring skilled care.", ["T81.31XA"],
        "Training Blue Shield", "SYN-BS-1011", [WOUND_EVAL, WEEKLY_WOUND],
    ),
    _case(
        "discharge-samuel-ortega", "discharge_packet", "clinical packet without explicit service", "fax",
        "ORTEGA, SAMUEL", "07/31/1960", "Male", "(760) 555-4112",
        "18 Scenario Circle, Victorville, CA 92392", "SYN1012",
        "Barstow Community Training Hospital", "Hannah Cole, RN",
        "Chronic ulcer of left ankle documented at discharge.", ["L97.329"],
        "SampleCare Dual Plan", "SYN-DUAL-1012", [], outcome="manual_review_required",
    ),
    _case(
        "agency-nora-whitfield", "agency_summary", "complete agency summary", "clean",
        "WHITFIELD, NORA", "01/22/1955", "Female", "(720) 555-4113",
        "17950 Example Drive, Aurora, CO 80015", "SYN1013",
        "AY Training Home Health", "Heather Koh, MD",
        "Unstageable pressure ulcer of sacral region.", ["L89.150"],
        "Example Medicare", "SYN-MCR-1013", [WOUND_EVAL],
    ),
    _case(
        "agency-harold-chen", "agency_summary", "no requested service stated", "fax",
        "CHEN, HAROLD", "09/09/1946", "Male", "(720) 555-4114",
        "804 Test Data Lane, Lakewood, CO 80215", "SYN1014",
        "AY Training Home Health", "Monica Hale, MD",
        "Diabetic ulcer of left midfoot.", ["E11.621", "L97.429"],
        "Sample Medicaid", "SYN-MCD-1014", [], outcome="manual_review_required",
    ),
)
